---

- hosts: all
  serial: 1
  tasks:
  - name: Pause the worker
    shell: ocluster-admin -c ~/admin.cap pause --wait macos-{{ ansible_architecture }} {{ inventory_hostname_short }}
    delegate_to: 127.0.0.1

  - name: Install Software Updates
    command: softwareupdate -i -a -R
    register: update
    async: 7200
    poll: 60
    become: yes
    changed_when: update.rc !=0 and 'No updates are available.' not in update.stderr

  - debug: var=update.stdout_lines

  - name: Reboot
    reboot:
    become: yes

  - name: Unpause the worker
    shell: ocluster-admin -c ~/admin.cap unpause macos-{{ ansible_architecture }} {{ inventory_hostname_short }}
    delegate_to: 127.0.0.1

