# DMG Installer
---
- name: Get DMG url
  get_url: url={{ dmgURL }} dest=/tmp/{{ pkgName }}.dmg
- name: Mount DMG
  command: hdiutil attach /tmp/{{ pkgName }}.dmg -nobrowse
- name: Install PKG
  become: yes
  shell: "installer -pkg /Volumes/{{ pkgName }}/{{ pkg }}.pkg \
  -target {{ target }}"
- name: Unmount DMG
  command: hdiutil detach /Volumes/{{ pkgName }}
